### ISSUE TITLE
WeasyPrint v. 50 not working

### ISSUE THREAD

**Issue by avarone-github** [comwes/mkpdfs-mkdocs-plugin#10]
I installed WeasyPrint v. 50 and I get the [attached error](https://github.com/comwes/mkpdfs-mkdocs-plugin/files/3933365/WeasyPrint.50.-.Error.txt).
I then re-installed v. 48 I used before and everything is fine.

**Comment by lavahot** [comment]
@avarone-github , are you still having this issue?

**Comment by avarone-github** [comment]
@lavahot:
v. 48: no
v. 50: yes
v. 51: no
So one solution can be using v. 51.

**Comment by trogper** [comment]
I suppose the issue is specific to your content. Can you try to isolate the issue?
e.g. remove files until the error disappears. I'm using wasyprint==50 just fine

**Comment by avarone-github** [comment]
@trogper: maybe, but I don't have time now for this test, so I'm closing this issue. I'm currently using v. 51 and I'm experimenting another kind of problem: WeasyPrint silently crashes after a while without producing the PDF. It must be said my documents are quite large (hundreds of pages) so maybe I've reached some limit. Thank you.

**Comment by trogper** [comment]
@avarone-github check your ram usage as the html for pdf generation is kept only in ram
