### ISSUE TITLE
AttributeError: module 'mkdocs.utils' has no attribute 'string_types'

### ISSUE THREAD

**Issue by jmborer** [comwes/mkpdfs-mkdocs-plugin#16]
Hi,

Apparently mkdpdfs is not compatible with mkdocs 1.1: mkdocs.utils.string_types seems to no longer exist.

beautifulsoup4==4.9.0
cairocffi==1.1.0
CairoSVG==2.4.2
cffi==1.14.0
click==7.1.2
cssselect2==0.3.0
defusedxml==0.6.0
future==0.18.2
html5lib==1.0.1
Jinja2==2.11.2
joblib==0.14.1
livereload==2.6.1
lunr==0.5.6
Markdown==3.2.1
markdown-captions==2
markdown-figcap==0.1.1
markdown-include==0.5.1
MarkupSafe==1.1.1
mkdocs==1.1
mkdocs-material==5.1.3
mkdocs-material-extensions==1.0b2
mkdocs-pdf-export-plugin==0.5.6
mkpdfs-mkdocs==1.0.1
nltk==3.5
Pillow==7.1.2
pycparser==2.20
Pygments==2.6.1
pymdown-extensions==7.1
Pyphen==0.9.5
PyYAML==5.3.1
regex==2020.4.4
six==1.14.0
soupsieve==2.0
tinycss2==1.0.2
tornado==6.0.4
tqdm==4.45.0
WeasyPrint==51
webencodings==0.5.1

**Comment by lavahot** [comment]
Does an earlier version of mkdocs still work?

**Comment by jmborer** [comment]
I don't know, I need the latest version of MkDocs. Here is working code:

class Mkpdfs(BasePlugin):
    config_scheme = (
        ('design', config_options.Type(str, default=None)),
        ('toc_title', config_options.Type(str, default="Table of Contents")),
        ('company', config_options.Type(str, default=None)),
        ('author', config_options.Type(str, default=None)),
        ('toc_position', config_options.Type(str, default="pre")),
        ('output_path', config_options.Type(str, default="pdf/combined.pdf")),
        ('embed_pdf_link', config_options.Type(bool, default=True)),
    )
