### ISSUE TITLE
Can't render properly

### ISSUE THREAD

**Issue by lavahot** [comwes/mkpdfs-mkdocs-plugin#19]
I've been banging my head on this for a while. When the PDF gets rendered the images are all large and span off the right side of the page. I get no errors or warnings during this time. I went ahead and tried to build this plugin's own docs and got the same result. The content is all there, but it looks nothing like the official doc PDF that is distributed. I've followed the WeasyPrint dependency installation to the letter. It's almost like the theme isn't applied for some reason.

**Comment by trogper** [comment]
you get no blue lines and headings? If so, the sass/scss did not get compiled into css.
this has been 'solved' in issue 12: <https://github.com/comwes/mkpdfs-mkdocs-plugin/issues/12#issuecomment-623056467>

**Comment by lavahot** [comment]
Yes exactly. Oh this was exactly what I was looking for. In fact, I found it about a half an hour ago. That answer is a little confusing, any chance you've got some automation to do this?

**Comment by trogper** [comment]
what level of automation do you mean?
``` bash
apt install nodejs npm
#maybe change paths
cd /usr/local/lib/python3.5/dist-packages/mkpdfs_mkdocs/design/
npm install
npm build-css
```
I'm new to this plugin, so I don't know much, but there's some design.py which should recompile css, buy it still needs the dependencies
