### ISSUE TITLE
Installing Plugin in Virtual Environment

### ISSUE THREAD

**Issue by ventolinmono** [comwes/mkpdfs-mkdocs-plugin#31]
How can i install the mkpdfs-mkdocs-plugin in a python virtual environment?
Tried it inside my Mkdocs folder but it was a mess.
New to pip. I already fixed my install but i don't get how to work in a virtual environment with Mkdocs and plugins and couldn't find specific references on this.

**Comment by comwes** [comment]
Hi @ventolinmono,

Is this still needed?

KR,
Gerry N.

**Comment by ventolinmx** [comment]
Didn't manage to figure this one out but I'm not working on this anymore so you can close the issue. Thanks for asking.

> Hi @ventolinmono,
> 
> Is this still needed?
> 
> KR,
> Gerry N.

**Comment by comwes** [comment]
Thanks for your feedback.
