### ISSUE TITLE
Add a test in order to test issue such the one reported in here

### ISSUE THREAD

**Issue by comwes** [comwes/mkpdfs-mkdocs-plugin#41]
Now I remember what the issue was. It was caused, I think, by mkdocs itself.
When you had heading on a page with diacritics, the element id (used for hash navigation) skipped diacritical letters (heading "Červená máňa" had id "erven-ma") which was very impractical. We resorted to using uslugify, which stripped only diacriticals, not whole letters.
You can probably take my comments just as a "reminder" to test tolerance to unicode characters

_Originally posted by @trogper in https://github.com/comwes/mkpdfs-mkdocs-plugin/issues/35#issuecomment-843328558_

**Comment by comwes** [comment]
@trogper  as you can see in the joined pdf, your exemple is working as expected. I think the problem might probably occur with python2 which we are planning to no longer support starting the upcoming release.

[docu-test.pdf](https://github.com/comwes/mkpdfs-mkdocs-plugin/files/6507047/docu-test.pdf)

KR,
@comwes

**Comment by trogper** [comment]
actually the link in `Second topic` does not work.
is it linked to the first topic or to červená máňa?

**Comment by comwes** [comment]
Indeed that link does not work because the page it is supposed to reference does not exist in the generated pdf which is normal.
