### ISSUE TITLE
Error when serve

### ISSUE THREAD

**Issue by jimlyas** [comwes/mkpdfs-mkdocs-plugin#44]
So i've installed the plugin following the `getting started`.

But when i run the command `mkdocs serve`, i'm getting this error
```shell
INFO    -  Building documentation... 

no library called "cairo" was found
no library called "libcairo-2" was found
cannot load library 'libcairo.so.2': error 0x7e   
cannot load library 'libcairo.2.dylib': error 0x7e
cannot load library 'libcairo-2.dll': error 0x7e 
```

Is there any step or something that i skipped?

**Comment by comwes** [comment]
Dear  @jimlyas,

That's normal as you can see here [Documentation > Requirements](https://github.com/comwes/mkpdfs-mkdocs-plugin#requirements) You have to install those requirements and your problem will be solved.

KR,
Gerry N.
